# :schema node_modules/wrangler/config-schema.json
name = "cloudflare-worker"
main = "src/index.ts"
compatibility_date = "2024-10-29"
compatibility_flags = [ "nodejs_compat" ]

[[r2_buckets]]
binding = 'MY_BUCKET'
bucket_name = 'files'

[observability.logs]
enabled = true

[[routes]]
pattern = "api.ckvv.net"
custom_domain = true
